model_params:
  n_estimators: 100
  random_state: 42

training_params:
  test_size: 0.2
  random_state: 42

features:
  categorical:
    - Gender
    - Subscription Type
    - Contract Length
  numerical:
    - tenure_months
    - monthly_charges
    - total_charges